name: Deploy My Linux VMs Using Terraform

on:
  push:
    branches:
      - main    
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}
      
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Verify Azure Connection
        run: |
          az account show

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/part5

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./infra/part5
  
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra/part5
      
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./infra/part5

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra/part5